### ISSUE TITLE
Add List of Users

### ISSUE THREAD

**Issue by nlchitnis** [umutphp/github-action-dynamic-profile-page#8]
Hi, Thanks for this amazing action. I was thinking, maybe we should add a list of current users in the README that way more people will use it. Like [Ammol098/Waka-Readme-Stats](https://github.com/anmol098/waka-readme-stats).

**Comment by nlchitnis** [comment]
I mean listing users (who use this action) in their Profile README

**Comment by nlchitnis** [comment]
I can work on this!

**Comment by nlchitnis** [comment]
No Problem

**Comment by nlchitnis** [comment]
I can always Update it when New People use the Action

**Comment by rishichitnis008** [comment]
I am willing to help as well!!

**Comment by Justgoncaa** [comment]
I am also willing to help as well!!

**Comment by LiamJao** [comment]
I'm also willing to help!!
